// ── Product Catalog Schema + Curated Data ──────────────────────────
// 100+ products curated for Present Agent's gift recommendation engine.
// Every product is enriched with gift intelligence metadata that encodes
// relationship psychology, giver motivations, and recipient fit.
//
// Sources: Web research (Mar 2026), verified Canadian pricing + shipping.
// Products are chosen for giftability, not just quality — each one must
// make sense as something you'd give someone, not just buy for yourself.

export interface Product {
  id: string;
  name: string;
  brand: string;
  price: number; // CAD
  currency: "CAD";
  category: "practical" | "experiential" | "consumable" | "artisan" | "wellness" | "kids";
  imageUrl: string;
  buyUrl: string;
  shortDescription: string;

  // Qualitative metadata for relationship-context matching
  meta: {
    psychologicalFit: ("practical" | "thoughtful" | "playful" | "luxurious" | "sentimental" | "adventurous")[];
    relationshipFit: ("partner" | "parent" | "child" | "close_family" | "friend" | "professional" | "acquaintance")[];
    recipientTraits: string[];
    recipientAge?: string[]; // "0-2" | "3-5" | "6-11" | "12-17" | "18-25" | "26-40" | "41-60" | "61+"
    occasionFit: ("birthday" | "mothers_day" | "fathers_day" | "anniversary" | "thank_you" | "housewarming" | "wedding" | "graduation" | "retirement" | "christmas" | "valentines" | "just_because" | "baby_shower" | "new_baby")[];
    effortSignal: "low_effort" | "moderate_effort" | "high_effort";
    priceTier: "token" | "budget" | "moderate" | "premium" | "luxury";
    giftable: true;
    isLastMinute?: boolean; // Digital/instant delivery
    usageSignal?: string; // "She'll use this every morning"
    whatThisSays?: string; // "This says: 'I see your daily ritual'"
  };
}

export type PriceTier = Product["meta"]["priceTier"];

export function priceTierFromBudget(budget: string | undefined): PriceTier[] {
  if (!budget) return ["token", "budget", "moderate", "premium", "luxury"];
  const nums = budget.match(/\d+/g)?.map(Number) || [];
  const max = nums.length > 0 ? Math.max(...nums) : 0;
  if (max <= 25) return ["token"];
  if (max <= 50) return ["token", "budget"];
  if (max <= 100) return ["token", "budget", "moderate"];
  if (max <= 200) return ["budget", "moderate", "premium"];
  if (max <= 400) return ["moderate", "premium", "luxury"];
  return ["premium", "luxury"];
}

// ══════════════════════════════════════════════════════════════════════
// CATALOG — 100+ curated gift products
// ══════════════════════════════════════════════════════════════════════

export const CATALOG: Product[] = [

  // ── PRACTICAL: Kitchen & Cooking ──────────────────────────────────

  { id: "caraway-cookware-set", name: "Ceramic Cookware Duo", brand: "Caraway", price: 175, currency: "CAD", category: "practical", imageUrl: "/products/caraway.jpg", buyUrl: "https://www.carawayhome.com/products/cookware-duo", shortDescription: "Non-toxic ceramic fry pan + sauce pan in matte finish. Beautiful enough to hang on the wall.", meta: { psychologicalFit: ["practical", "thoughtful"], relationshipFit: ["partner", "parent", "close_family", "friend"], recipientTraits: ["cooking", "foodie", "home", "design", "minimalist", "health-conscious"], occasionFit: ["birthday", "housewarming", "wedding", "christmas", "mothers_day"], effortSignal: "moderate_effort", priceTier: "premium", giftable: true, usageSignal: "She'll reach for these every time she cooks", whatThisSays: "I notice you care about what goes into your food" } },

  { id: "our-place-always-pan", name: "Always Pan 2.0", brand: "Our Place", price: 200, currency: "CAD", category: "practical", imageUrl: "/products/always-pan.jpg", buyUrl: "https://fromourplace.ca/products/always-pan", shortDescription: "Replaces 8 pieces of cookware. Toxin-free, gorgeous colors. Steams, sears, sautés, fries.", meta: { psychologicalFit: ["practical", "thoughtful"], relationshipFit: ["partner", "parent", "close_family", "friend", "professional"], recipientTraits: ["cooking", "foodie", "minimalist", "design", "home"], occasionFit: ["wedding", "housewarming", "birthday", "mothers_day", "christmas"], effortSignal: "moderate_effort", priceTier: "premium", giftable: true, usageSignal: "This becomes the one pan they reach for every single night", whatThisSays: "I want to make your kitchen feel as good as your cooking" } },

  { id: "fellow-kettle", name: "Stagg EKG Electric Kettle", brand: "Fellow", price: 230, currency: "CAD", category: "practical", imageUrl: "/products/fellow-kettle.jpg", buyUrl: "https://fellowproducts.com/products/stagg-ekg-electric-gooseneck-kettle", shortDescription: "Precision pour-over kettle with LCD display. Gorgeous matte black. For the coffee/tea person.", meta: { psychologicalFit: ["practical", "luxurious", "thoughtful"], relationshipFit: ["partner", "parent", "friend", "close_family"], recipientTraits: ["coffee", "tea", "design", "minimalist", "foodie", "cooking"], occasionFit: ["birthday", "housewarming", "wedding", "christmas", "thank_you"], effortSignal: "high_effort", priceTier: "premium", giftable: true, usageSignal: "This becomes the centerpiece of their morning ritual", whatThisSays: "I know your morning coffee matters to you" } },

  { id: "fellow-pourover-set", name: "Stagg [XF] Pour-Over Set", brand: "Fellow", price: 143, currency: "CAD", category: "practical", imageUrl: "/products/fellow-pourover.jpg", buyUrl: "https://eightouncecoffee.ca/products/fellow-stagg-xf-pour-over-set", shortDescription: "Complete 2-cup pour-over system with vacuum-insulated dripper and glass carafe. The most photogenic pour-over kit on the market.", meta: { psychologicalFit: ["practical", "thoughtful", "luxurious"], relationshipFit: ["partner", "friend", "close_family", "professional"], recipientTraits: ["coffee", "design", "minimalist", "morning-person"], occasionFit: ["birthday", "housewarming", "christmas", "thank_you", "just_because"], effortSignal: "high_effort", priceTier: "moderate", giftable: true, usageSignal: "A whole new morning ritual, one slow pour at a time", whatThisSays: "I want you to have a reason to slow down every morning" } },

  { id: "ember-mug", name: "Temperature Control Mug", brand: "Ember", price: 170, currency: "CAD", category: "practical", imageUrl: "/products/ember.jpg", buyUrl: "https://ember.com/products/ember-mug-2", shortDescription: "Keeps your drink at the exact temperature you want. App-controlled. Never cold coffee again.", meta: { psychologicalFit: ["practical", "luxurious"], relationshipFit: ["partner", "parent", "professional", "friend"], recipientTraits: ["coffee", "tea", "tech", "wfh", "office", "practical"], occasionFit: ["birthday", "christmas", "thank_you", "fathers_day", "mothers_day", "retirement"], effortSignal: "moderate_effort", priceTier: "premium", giftable: true, usageSignal: "They'll never drink a cold coffee again", whatThisSays: "I know you get distracted and your coffee goes cold — fixed" } },

  // ── PRACTICAL: Tech & Gadgets ─────────────────────────────────────

  { id: "anker-soundcore-speaker", name: "Motion 300 Portable Speaker", brand: "Soundcore", price: 80, currency: "CAD", category: "practical", imageUrl: "/products/soundcore.jpg", buyUrl: "https://www.soundcore.com/products/motion-300-a3135", shortDescription: "Compact wireless speaker with spatial audio. Waterproof, 13hr battery. Great for outdoors.", meta: { psychologicalFit: ["practical", "playful"], relationshipFit: ["friend", "close_family", "partner"], recipientTraits: ["music", "outdoors", "tech", "active", "minimalist"], occasionFit: ["birthday", "christmas", "graduation", "thank_you"], effortSignal: "moderate_effort", priceTier: "moderate", giftable: true, usageSignal: "Goes everywhere — kitchen, backyard, beach, camping trips", whatThisSays: "I want music to follow you wherever you go" } },

  // ── PRACTICAL: Outdoor & Active ───────────────────────────────────

  { id: "yeti-tumbler", name: "Rambler 20oz Tumbler", brand: "YETI", price: 45, currency: "CAD", category: "practical", imageUrl: "/products/yeti.jpg", buyUrl: "https://www.yeti.ca/drinkware/tumblers/rambler-20-oz-tumbler/21070060018.html", shortDescription: "Indestructible insulated tumbler. Keeps hot drinks hot, cold drinks cold. Everyone needs one.", meta: { psychologicalFit: ["practical"], relationshipFit: ["friend", "close_family", "acquaintance", "professional", "parent"], recipientTraits: ["outdoors", "coffee", "tea", "practical", "active", "office", "commuter"], occasionFit: ["birthday", "christmas", "thank_you", "housewarming", "just_because", "fathers_day"], effortSignal: "low_effort", priceTier: "budget", giftable: true, usageSignal: "Becomes their daily driver for every drink", whatThisSays: "Simple, indestructible, just like our friendship" } },

  // ── EXPERIENTIAL: Learning & Growth ───────────────────────────────

  { id: "masterclass-annual", name: "Annual Membership", brand: "MasterClass", price: 140, currency: "CAD", category: "experiential", imageUrl: "/products/masterclass.jpg", buyUrl: "https://www.masterclass.com/gift", shortDescription: "200+ classes from world experts. Cooking, writing, music, business, wellness. Gift-wrapped email.", meta: { psychologicalFit: ["thoughtful", "adventurous"], relationshipFit: ["partner", "parent", "close_family", "friend", "professional"], recipientTraits: ["curious", "learning", "cooking", "creative", "reading", "music", "business"], occasionFit: ["birthday", "christmas", "graduation", "retirement", "thank_you", "fathers_day", "mothers_day"], effortSignal: "moderate_effort", priceTier: "moderate", giftable: true, isLastMinute: true, usageSignal: "A new world-class teacher every weekend", whatThisSays: "I believe in your curiosity" } },

  { id: "skillshare-annual", name: "Annual Membership", brand: "Skillshare", price: 168, currency: "CAD", category: "experiential", imageUrl: "/products/skillshare.jpg", buyUrl: "https://www.skillshare.com/en/pricing", shortDescription: "30,000+ creative classes in illustration, design, photography, music, writing. Learn by doing.", meta: { psychologicalFit: ["thoughtful", "adventurous"], relationshipFit: ["partner", "friend", "close_family"], recipientTraits: ["creative", "art", "design", "photography", "music", "learning"], occasionFit: ["birthday", "christmas", "graduation", "just_because"], effortSignal: "moderate_effort", priceTier: "moderate", giftable: true, isLastMinute: true, usageSignal: "A new creative skill every month", whatThisSays: "I see your creative side and want to fuel it" } },

  { id: "book-of-the-month-6", name: "6-Month Gift Subscription", brand: "Book of the Month", price: 137, currency: "CAD", category: "experiential", imageUrl: "/products/botm.jpg", buyUrl: "https://www.bookofthemonth.com/gift", shortDescription: "Curated book subscription — pick one new hardcover each month from five expert selections.", meta: { psychologicalFit: ["thoughtful"], relationshipFit: ["partner", "parent", "friend", "close_family"], recipientTraits: ["reading", "books", "curious", "literary"], occasionFit: ["birthday", "christmas", "mothers_day", "fathers_day", "just_because"], effortSignal: "high_effort", priceTier: "moderate", giftable: true, usageSignal: "A new book every month, chosen just for them", whatThisSays: "I know you lose yourself in a good book" } },

  { id: "criterion-channel-6mo", name: "6-Month Gift Subscription", brand: "The Criterion Channel", price: 90, currency: "CAD", category: "experiential", imageUrl: "/products/criterion.jpg", buyUrl: "https://www.criterionchannel.com/checkout/subscribe/gift", shortDescription: "Curated streaming for cinephiles — classic, art-house, and international cinema with exclusive extras.", meta: { psychologicalFit: ["thoughtful"], relationshipFit: ["partner", "friend", "close_family"], recipientTraits: ["film", "cinema", "art", "creative", "curious"], occasionFit: ["birthday", "christmas", "valentines", "just_because"], effortSignal: "high_effort", priceTier: "moderate", giftable: true, isLastMinute: true, usageSignal: "Movie nights just got a serious upgrade", whatThisSays: "This is for the person who knows Kurosawa from Kubrick" } },

  { id: "audible-3mo", name: "3-Month Premium Plus Gift", brand: "Audible Canada", price: 45, currency: "CAD", category: "experiential", imageUrl: "/products/audible.jpg", buyUrl: "https://www.audible.ca/mk/g/giftcentre", shortDescription: "3 audiobook credits plus unlimited access to the Audible Plus catalog. Perfect for commuters.", meta: { psychologicalFit: ["practical", "thoughtful"], relationshipFit: ["friend", "professional", "parent", "close_family", "acquaintance"], recipientTraits: ["reading", "books", "commuter", "multitasker", "podcast"], occasionFit: ["birthday", "christmas", "thank_you", "just_because"], effortSignal: "low_effort", priceTier: "budget", giftable: true, isLastMinute: true, usageSignal: "A great book for every commute, walk, and workout", whatThisSays: "For someone who never has time to sit and read" } },

  // ── EXPERIENTIAL: Food & Drink Experiences ────────────────────────

  { id: "airbnb-experience-gift", name: "Experience Gift Card", brand: "Airbnb Experiences", price: 100, currency: "CAD", category: "experiential", imageUrl: "/products/airbnb-exp.jpg", buyUrl: "https://www.airbnb.ca/giftcards/buy", shortDescription: "Local experiences — cooking classes, art tours, outdoor adventures. They choose what excites them.", meta: { psychologicalFit: ["adventurous", "playful", "thoughtful"], relationshipFit: ["partner", "friend", "close_family"], recipientTraits: ["travel", "experiences", "foodie", "adventurous", "social", "active"], occasionFit: ["birthday", "anniversary", "graduation", "retirement", "valentines", "just_because"], effortSignal: "moderate_effort", priceTier: "moderate", giftable: true, isLastMinute: true, usageSignal: "They pick the adventure — cooking class, kayaking, gallery tour", whatThisSays: "I want you to have a story, not a thing" } },

  { id: "atlas-coffee-12mo", name: "12-Month World Tour Subscription", brand: "Atlas Coffee Club", price: 290, currency: "CAD", category: "experiential", imageUrl: "/products/atlas-coffee.jpg", buyUrl: "https://atlascoffeeclub.com/products/coffee-gift-subscriptions", shortDescription: "A different country's coffee every month — Ethiopia, Colombia, Indonesia — with tasting notes and postcards.", meta: { psychologicalFit: ["thoughtful", "adventurous"], relationshipFit: ["partner", "friend", "parent", "professional"], recipientTraits: ["coffee", "travel", "curious", "foodie"], occasionFit: ["birthday", "christmas", "fathers_day", "housewarming"], effortSignal: "high_effort", priceTier: "premium", giftable: true, usageSignal: "A new origin story in their cup every month for a year", whatThisSays: "I know your morning coffee is sacred — this makes it an adventure" } },

  { id: "tinggly-fun-together", name: "Fun Together Experience Box", brand: "Tinggly", price: 95, currency: "CAD", category: "experiential", imageUrl: "/products/tinggly.jpg", buyUrl: "https://tinggly.com/collection/fun-together/TPTR241FP", shortDescription: "A gift box with 1,000+ experiences worldwide — spa days, food tours, adventure sports. They choose.", meta: { psychologicalFit: ["adventurous", "playful"], relationshipFit: ["partner", "friend", "close_family"], recipientTraits: ["experiences", "travel", "adventurous", "social", "active"], occasionFit: ["birthday", "anniversary", "valentines", "graduation", "just_because"], effortSignal: "moderate_effort", priceTier: "moderate", giftable: true, usageSignal: "They pick from 1,000+ experiences in 90 countries", whatThisSays: "Let's make a memory, not add to the clutter" } },

  // ── EXPERIENTIAL: Entertainment & Digital ─────────────────────────

  { id: "spotify-12mo", name: "12-Month Premium Gift Card", brand: "Spotify", price: 99, currency: "CAD", category: "experiential", imageUrl: "/products/spotify.jpg", buyUrl: "https://www.walmart.ca/en/ip/spotify-premium-digital-gift-card-99/6000211015972", shortDescription: "A year of ad-free music, podcasts, and offline downloads. The most universally useful digital gift.", meta: { psychologicalFit: ["practical", "playful"], relationshipFit: ["friend", "close_family", "partner", "acquaintance", "professional"], recipientTraits: ["music", "podcast", "commuter", "tech"], occasionFit: ["birthday", "christmas", "graduation", "thank_you", "just_because"], effortSignal: "low_effort", priceTier: "moderate", giftable: true, isLastMinute: true, usageSignal: "Music and podcasts, ad-free, every single day", whatThisSays: "Soundtrack to your year, on me" } },

  { id: "uncommon-goods-date-night", name: "Scratch-Off Date Night Book", brand: "Uncommon Goods", price: 35, currency: "CAD", category: "experiential", imageUrl: "/products/date-night.jpg", buyUrl: "https://www.uncommongoods.com/product/scratch-off-date-night-book", shortDescription: "50 scratch-off date ideas from chill to adventurous. Decide together, reveal the surprise.", meta: { psychologicalFit: ["playful", "adventurous", "sentimental"], relationshipFit: ["partner"], recipientTraits: ["romantic", "fun", "social", "adventurous", "experiences"], occasionFit: ["anniversary", "valentines", "birthday", "christmas", "just_because"], effortSignal: "moderate_effort", priceTier: "budget", giftable: true, usageSignal: "One scratch-off per week = a year of spontaneous dates", whatThisSays: "I want us to keep being spontaneous together" } },

  // ── CONSUMABLE: Coffee & Tea ──────────────────────────────────────

  { id: "trade-coffee-sub", name: "Coffee Subscription (3 months)", brand: "Trade Coffee", price: 65, currency: "CAD", category: "consumable", imageUrl: "/products/trade-coffee.jpg", buyUrl: "https://www.drinktrade.com/pages/gift", shortDescription: "Personalized coffee matched to their taste. Fresh-roasted, delivered monthly. Gift card included.", meta: { psychologicalFit: ["thoughtful", "practical"], relationshipFit: ["friend", "professional", "acquaintance", "close_family", "partner"], recipientTraits: ["coffee", "foodie", "morning-person", "minimalist", "practical"], occasionFit: ["thank_you", "birthday", "christmas", "housewarming", "just_because", "fathers_day"], effortSignal: "high_effort", priceTier: "moderate", giftable: true, usageSignal: "Fresh beans on their doorstep every month", whatThisSays: "I know your morning starts with a good cup" } },

  { id: "detour-coffee-sub", name: "Single Origin Subscription", brand: "Detour Coffee", price: 43, currency: "CAD", category: "consumable", imageUrl: "/products/detour.jpg", buyUrl: "https://detourcoffee.com/products/single-origin-coffee-subscription", shortDescription: "Rotating seasonal single-origin coffees from Ontario's top roaster. Free shipping across Canada.", meta: { psychologicalFit: ["thoughtful", "practical"], relationshipFit: ["friend", "professional", "partner", "close_family"], recipientTraits: ["coffee", "foodie", "local", "minimalist"], occasionFit: ["birthday", "christmas", "thank_you", "just_because", "housewarming"], effortSignal: "moderate_effort", priceTier: "budget", giftable: true, usageSignal: "A different farm in their cup every month", whatThisSays: "I signed you up for a monthly surprise from one of Ontario's best" } },

  { id: "davidstea-chai-wheel", name: "Chai Teas Sachet Tea Wheel", brand: "DAVIDsTEA", price: 49, currency: "CAD", category: "consumable", imageUrl: "/products/davidstea.jpg", buyUrl: "https://davidstea.com/collections/gifts-under-50", shortDescription: "Visually striking wheel of assorted chai sachets — spin, pick, steep. Canadian brand, gift-ready.", meta: { psychologicalFit: ["playful", "thoughtful"], relationshipFit: ["friend", "parent", "professional", "acquaintance", "close_family"], recipientTraits: ["tea", "cozy", "home", "relaxation"], occasionFit: ["birthday", "christmas", "thank_you", "housewarming", "just_because", "mothers_day"], effortSignal: "moderate_effort", priceTier: "budget", giftable: true, usageSignal: "Spin the wheel, pick a chai — a different flavour every afternoon", whatThisSays: "Something cozy for your kitchen counter" } },

  { id: "harney-sons-holiday", name: "Holiday Teas Gift Set", brand: "Harney & Sons", price: 43, currency: "CAD", category: "consumable", imageUrl: "/products/harney.jpg", buyUrl: "https://premiumteas.ca/products/harney-sons-holiday-teas-gift-set", shortDescription: "Two tins of premium silken sachets — citrus/almond/clove and cardamom/vanilla — in a silk-ribbon gift box.", meta: { psychologicalFit: ["thoughtful", "luxurious"], relationshipFit: ["parent", "friend", "professional", "acquaintance", "close_family"], recipientTraits: ["tea", "elegant", "home", "relaxation", "cozy"], occasionFit: ["christmas", "thank_you", "birthday", "mothers_day", "just_because"], effortSignal: "moderate_effort", priceTier: "budget", giftable: true, usageSignal: "The kind of tea you brew when you want a moment to yourself", whatThisSays: "Something elegant for your quiet moments" } },

  // ── CONSUMABLE: Food & Treats ─────────────────────────────────────

  { id: "goldbelly-local-eats", name: "Iconic Eats Box", brand: "Goldbelly", price: 95, currency: "CAD", category: "consumable", imageUrl: "/products/goldbelly.jpg", buyUrl: "https://www.goldbelly.com/gifts", shortDescription: "Famous restaurant dishes shipped nationwide. NYC pizza, southern BBQ, Magnolia cupcakes.", meta: { psychologicalFit: ["playful", "luxurious", "thoughtful"], relationshipFit: ["friend", "close_family", "partner", "parent"], recipientTraits: ["foodie", "cooking", "travel", "nostalgic", "adventurous"], occasionFit: ["birthday", "thank_you", "christmas", "just_because", "anniversary"], effortSignal: "high_effort", priceTier: "moderate", giftable: true, usageSignal: "A legendary restaurant meal, delivered to their kitchen", whatThisSays: "I remember you talking about that place — here it is" } },

  { id: "compartes-chocolate", name: "Gourmet Chocolate Bar Collection (4 bars)", brand: "Compartes", price: 50, currency: "CAD", category: "consumable", imageUrl: "/products/compartes.jpg", buyUrl: "https://campbrandgoods.com/collections/compartes-chocolate", shortDescription: "LA's iconic art-meets-chocolate bars — S'mores, Donuts & Coffee, Matcha, Salted Pistachio. From a Canadian retailer.", meta: { psychologicalFit: ["playful", "luxurious"], relationshipFit: ["friend", "professional", "acquaintance", "partner", "close_family"], recipientTraits: ["foodie", "chocolate", "design", "art"], occasionFit: ["birthday", "christmas", "thank_you", "just_because", "valentines"], effortSignal: "moderate_effort", priceTier: "budget", giftable: true, usageSignal: "Four conversation pieces disguised as chocolate bars", whatThisSays: "These are too beautiful to eat. Almost." } },

  { id: "batch-cocktail-kit", name: "Craft Cocktail Kit", brand: "Batch & Bottle", price: 55, currency: "CAD", category: "consumable", imageUrl: "/products/cocktail-kit.jpg", buyUrl: "https://www.hendricksgin.com/en-ca/batch-and-bottle/", shortDescription: "Premium pre-mixed cocktails. Negroni, Old Fashioned, or Margarita. Just pour over ice.", meta: { psychologicalFit: ["playful", "luxurious"], relationshipFit: ["friend", "close_family", "professional", "acquaintance"], recipientTraits: ["cocktails", "hosting", "social", "foodie"], occasionFit: ["housewarming", "thank_you", "birthday", "christmas", "just_because"], effortSignal: "moderate_effort", priceTier: "moderate", giftable: true, usageSignal: "A bar-quality cocktail in 30 seconds flat", whatThisSays: "No shaker needed — just ice and good company" } },

  // ── ARTISAN: Home Fragrance ───────────────────────────────────────

  { id: "le-labo-candle", name: "Santal 26 Candle", brand: "Le Labo", price: 85, currency: "CAD", category: "artisan", imageUrl: "/products/le-labo.jpg", buyUrl: "https://www.lelabofragrances.com/santal-26-classic-candle.html", shortDescription: "Cult-favorite luxury candle. Smoky sandalwood, amber, cedar. Hand-poured in Brooklyn.", meta: { psychologicalFit: ["luxurious", "thoughtful"], relationshipFit: ["partner", "friend", "professional", "close_family", "acquaintance"], recipientTraits: ["home", "design", "luxury", "relaxation", "aesthetic"], occasionFit: ["housewarming", "birthday", "thank_you", "christmas", "mothers_day", "valentines", "just_because"], effortSignal: "moderate_effort", priceTier: "moderate", giftable: true, usageSignal: "The scent they'll associate with feeling at home", whatThisSays: "I notice you care about your space" } },

  { id: "vitruvi-diffuser", name: "Stone Diffuser", brand: "Vitruvi", price: 140, currency: "CAD", category: "artisan", imageUrl: "/products/vitruvi.jpg", buyUrl: "https://www.vitruvi.com/products/stone-diffuser", shortDescription: "Hand-finished porcelain essential oil diffuser. Whisper-quiet. Doubles as décor.", meta: { psychologicalFit: ["thoughtful", "luxurious"], relationshipFit: ["partner", "parent", "close_family", "friend", "professional"], recipientTraits: ["wellness", "design", "minimalist", "home", "yoga", "relaxation"], occasionFit: ["birthday", "mothers_day", "housewarming", "christmas", "thank_you", "valentines"], effortSignal: "high_effort", priceTier: "moderate", giftable: true, usageSignal: "She'll turn it on every evening when the day winds down", whatThisSays: "I want your home to feel like a sanctuary" } },

  // ── ARTISAN: Stationery & Paper ───────────────────────────────────

  { id: "poketo-planner", name: "Spectrum Planner", brand: "Poketo", price: 45, currency: "CAD", category: "artisan", imageUrl: "/products/poketo.jpg", buyUrl: "https://www.poketo.com/products/spectrum-planner", shortDescription: "Beautifully designed undated planner with color-coded sections. Art-meets-function.", meta: { psychologicalFit: ["thoughtful", "practical"], relationshipFit: ["friend", "close_family", "professional"], recipientTraits: ["design", "organized", "creative", "art", "stationery", "adhd"], occasionFit: ["birthday", "christmas", "graduation", "just_because", "thank_you"], effortSignal: "moderate_effort", priceTier: "budget", giftable: true, usageSignal: "The planner that actually gets used because it's too pretty to ignore", whatThisSays: "For someone who thinks in color" } },

  { id: "rifle-paper-journal", name: "Stitched Notebook Set", brand: "Rifle Paper Co.", price: 30, currency: "CAD", category: "artisan", imageUrl: "/products/rifle-paper.jpg", buyUrl: "https://riflepaperco.com/stitched-notebook-set-garden-party", shortDescription: "Set of 3 gorgeous floral notebooks. Gold foil details. Perfect for lists, journals, sketches.", meta: { psychologicalFit: ["thoughtful", "playful"], relationshipFit: ["friend", "professional", "acquaintance", "close_family"], recipientTraits: ["stationery", "writing", "creative", "art", "journaling", "organized"], occasionFit: ["birthday", "christmas", "thank_you", "just_because", "graduation"], effortSignal: "moderate_effort", priceTier: "budget", giftable: true, usageSignal: "Three notebooks that are almost too beautiful to write in. Almost.", whatThisSays: "For the person who always has a list going" } },

  // ── ARTISAN: Art & Custom ─────────────────────────────────────────

  { id: "custom-star-map", name: "Custom Star Map Print", brand: "Under Lucky Stars", price: 70, currency: "CAD", category: "artisan", imageUrl: "/products/star-map.jpg", buyUrl: "https://www.underluckystars.com/create", shortDescription: "The exact night sky from any date & location. Wedding night, birth of a child, first date.", meta: { psychologicalFit: ["sentimental", "thoughtful", "luxurious"], relationshipFit: ["partner", "parent", "close_family"], recipientTraits: ["sentimental", "romantic", "nostalgic", "home", "art"], occasionFit: ["anniversary", "wedding", "birthday", "valentines", "mothers_day", "fathers_day"], effortSignal: "high_effort", priceTier: "moderate", giftable: true, usageSignal: "A permanent reminder of the night everything changed", whatThisSays: "I remember that night too" } },

  // ── WELLNESS: Mind & Meditation ───────────────────────────────────

  { id: "headspace-annual", name: "Annual Subscription", brand: "Headspace", price: 90, currency: "CAD", category: "wellness", imageUrl: "/products/headspace.jpg", buyUrl: "https://www.headspace.com/buy/gift", shortDescription: "Meditation, sleep, and focus. Gift card version — activates when they're ready.", meta: { psychologicalFit: ["thoughtful", "practical"], relationshipFit: ["partner", "parent", "friend", "close_family"], recipientTraits: ["wellness", "meditation", "anxiety", "mindfulness", "stress", "adhd", "yoga"], occasionFit: ["birthday", "christmas", "just_because", "thank_you"], effortSignal: "moderate_effort", priceTier: "moderate", giftable: true, isLastMinute: true, usageSignal: "Ten minutes of calm, every single day", whatThisSays: "I see how hard you work — this is permission to pause" } },

  { id: "calm-annual", name: "1-Year Gift Subscription", brand: "Calm", price: 85, currency: "CAD", category: "wellness", imageUrl: "/products/calm.jpg", buyUrl: "https://www.calm.com/gift", shortDescription: "Guided meditations, celebrity sleep stories, breathing exercises, and calming music for a full year.", meta: { psychologicalFit: ["thoughtful", "practical"], relationshipFit: ["partner", "parent", "friend", "close_family", "professional"], recipientTraits: ["wellness", "sleep", "meditation", "stress", "anxiety", "relaxation"], occasionFit: ["birthday", "christmas", "just_because", "mothers_day", "thank_you"], effortSignal: "moderate_effort", priceTier: "moderate", giftable: true, isLastMinute: true, usageSignal: "She'll open this every night before bed", whatThisSays: "I want you to sleep well" } },

  { id: "waking-up-annual", name: "1-Year Gift Subscription", brand: "Waking Up", price: 130, currency: "CAD", category: "wellness", imageUrl: "/products/wakingup.jpg", buyUrl: "https://app.wakingup.com/purchase-gift-card", shortDescription: "Sam Harris's meditation app — neuroscience-rooted, philosophically deep. For the intellectual meditator.", meta: { psychologicalFit: ["thoughtful"], relationshipFit: ["partner", "friend", "close_family"], recipientTraits: ["meditation", "philosophy", "intellectual", "curious", "mindfulness"], occasionFit: ["birthday", "christmas", "just_because"], effortSignal: "high_effort", priceTier: "moderate", giftable: true, isLastMinute: true, usageSignal: "10 minutes with his morning coffee, every single day", whatThisSays: "For someone who thinks too much — in the best way" } },

  { id: "five-minute-journal", name: "The Five Minute Journal", brand: "Intelligent Change", price: 32, currency: "CAD", category: "wellness", imageUrl: "/products/5min-journal.jpg", buyUrl: "https://www.chapters.indigo.ca/en-ca/paper/the-five-minute-journal/9780991846207-item.html", shortDescription: "Structured daily gratitude journal — morning and evening prompts. Build a positive mindset in 5 minutes.", meta: { psychologicalFit: ["thoughtful", "practical"], relationshipFit: ["friend", "partner", "close_family", "professional", "acquaintance"], recipientTraits: ["journaling", "wellness", "mindfulness", "organized", "self-improvement"], occasionFit: ["birthday", "christmas", "just_because", "thank_you", "graduation"], effortSignal: "moderate_effort", priceTier: "budget", giftable: true, usageSignal: "Five minutes at the kitchen table every morning before the house wakes up", whatThisSays: "A small habit that changes everything" } },

  { id: "scoria-zafu-cushion", name: "Zafu Natural Meditation Cushion", brand: "Scoria", price: 94, currency: "CAD", category: "wellness", imageUrl: "/products/scoria-zafu.jpg", buyUrl: "https://www.scoria.ca/products/zafu-natural-meditation-cushion-shadow-grey", shortDescription: "Beautiful round pleated cushion filled with buckwheat hulls. Muted tones. Free shipping in Canada.", meta: { psychologicalFit: ["thoughtful", "luxurious"], relationshipFit: ["partner", "friend", "close_family"], recipientTraits: ["meditation", "yoga", "wellness", "design", "minimalist"], occasionFit: ["birthday", "christmas", "just_because", "mothers_day"], effortSignal: "high_effort", priceTier: "moderate", giftable: true, usageSignal: "Becomes their permanent spot on the living room floor", whatThisSays: "I want your practice to have a beautiful home" } },

  // ── WELLNESS: Movement & Fitness ──────────────────────────────────

  { id: "oura-ring", name: "Oura Ring Gen 4", brand: "Oura", price: 400, currency: "CAD", category: "wellness", imageUrl: "/products/oura.jpg", buyUrl: "https://ouraring.com/product/rings/oura-ring-4", shortDescription: "Sleep & health tracker in a minimal titanium ring. Tracks sleep, activity, heart rate, stress.", meta: { psychologicalFit: ["practical", "thoughtful", "luxurious"], relationshipFit: ["partner", "close_family"], recipientTraits: ["tech", "fitness", "wellness", "data", "health-conscious", "running", "yoga"], occasionFit: ["birthday", "anniversary", "christmas", "valentines"], effortSignal: "high_effort", priceTier: "luxury", giftable: true, usageSignal: "Worn 24/7 — the first thing they check every morning", whatThisSays: "Your health matters to me as much as it does to you" } },

  { id: "lululemon-mat", name: "The Reversible Mat 5mm", brand: "Lululemon", price: 98, currency: "CAD", category: "wellness", imageUrl: "/products/lulu-mat.jpg", buyUrl: "https://shop.lululemon.com/p/yoga-mats/The-Reversible-Mat-5/_/prod6750166", shortDescription: "Natural rubber yoga mat with antimicrobial additive. Grippy on both sides. Beautiful colors.", meta: { psychologicalFit: ["practical", "thoughtful"], relationshipFit: ["partner", "friend", "close_family"], recipientTraits: ["yoga", "pilates", "fitness", "wellness", "active"], occasionFit: ["birthday", "christmas", "mothers_day", "just_because"], effortSignal: "moderate_effort", priceTier: "moderate", giftable: true, usageSignal: "Unrolled every morning for the next decade", whatThisSays: "I support your practice" } },

  { id: "manduka-pro-mat", name: "PRO Yoga Mat 6mm", brand: "Manduka", price: 188, currency: "CAD", category: "wellness", imageUrl: "/products/manduka.jpg", buyUrl: "https://www.amazon.ca/Manduka-PRO-Yoga-Mat-FitnessExtra/dp/B08372TF5J", shortDescription: "The gold-standard professional yoga mat — ultra-dense, lifetime guarantee, closed-cell surface. Made in Germany.", meta: { psychologicalFit: ["practical", "luxurious", "thoughtful"], relationshipFit: ["partner", "close_family", "friend"], recipientTraits: ["yoga", "pilates", "fitness", "wellness", "dedicated"], occasionFit: ["birthday", "christmas", "mothers_day", "just_because", "anniversary"], effortSignal: "high_effort", priceTier: "premium", giftable: true, usageSignal: "The mat she unrolls every morning for the next decade", whatThisSays: "Your practice deserves the best" } },

  { id: "bala-bangles", name: "Bangles 1lb Wrist/Ankle Weights", brand: "Bala", price: 50, currency: "CAD", category: "wellness", imageUrl: "/products/bala.jpg", buyUrl: "https://well.ca/products/bala-bangles-classic-1lb-anklewrist_191019.html", shortDescription: "Design-forward wearable weights for walks, yoga, barre, and Pilates. Comes in pairs with a carrying pouch.", meta: { psychologicalFit: ["practical", "playful"], relationshipFit: ["friend", "partner", "close_family"], recipientTraits: ["fitness", "pilates", "barre", "yoga", "active", "walking", "design"], occasionFit: ["birthday", "christmas", "just_because", "mothers_day"], effortSignal: "moderate_effort", priceTier: "budget", giftable: true, usageSignal: "Strapped on for every morning walk", whatThisSays: "For someone who makes even exercise look stylish" } },

  { id: "theragun-mini", name: "Mini 2.0 Percussive Massage Gun", brand: "Therabody", price: 219, currency: "CAD", category: "wellness", imageUrl: "/products/theragun.jpg", buyUrl: "https://www.bestbuy.ca/en-ca/product/therabody-theragun-mini-plus-handheld-percussive-massage-device-black/19434303", shortDescription: "Pocket-sized percussion massage — three speeds, ultra-quiet. Goes in the gym bag, desk drawer, carry-on.", meta: { psychologicalFit: ["practical", "luxurious"], relationshipFit: ["partner", "parent", "close_family", "friend"], recipientTraits: ["fitness", "running", "gym", "active", "desk-worker", "travel"], occasionFit: ["birthday", "christmas", "fathers_day", "just_because"], effortSignal: "moderate_effort", priceTier: "premium", giftable: true, usageSignal: "In the gym bag after every workout — and at the desk on Mondays", whatThisSays: "You push hard. This helps you recover." } },

  // ── WELLNESS: Sleep & Rest ────────────────────────────────────────

  { id: "bearaby-weighted-blanket", name: "Cotton Napper Weighted Blanket (15lb)", brand: "Bearaby", price: 249, currency: "CAD", category: "wellness", imageUrl: "/products/bearaby.jpg", buyUrl: "https://www.amazon.ca/Bearaby-Cotton-Napper-Weighted-Blanket/dp/B0855J19YH", shortDescription: "Chunky-knit organic cotton weighted blanket — no beads, no fillers. Gorgeous on the couch.", meta: { psychologicalFit: ["thoughtful", "luxurious"], relationshipFit: ["partner", "parent", "close_family", "friend"], recipientTraits: ["sleep", "anxiety", "cozy", "home", "wellness", "relaxation"], occasionFit: ["birthday", "christmas", "just_because", "mothers_day", "valentines"], effortSignal: "high_effort", priceTier: "premium", giftable: true, usageSignal: "Wrapped in it every evening on the couch", whatThisSays: "I want you to feel held" } },

  { id: "hatch-restore", name: "Restore 2 Sunrise Alarm + Sound Machine", brand: "Hatch", price: 200, currency: "CAD", category: "wellness", imageUrl: "/products/hatch.jpg", buyUrl: "https://www.amazon.ca/Hatch-Restore-Machine-Personal-Routine/dp/B0C5S7K1JK", shortDescription: "Sunrise alarm clock + sound machine + sleep routines in one bedside device. App-controlled.", meta: { psychologicalFit: ["practical", "thoughtful"], relationshipFit: ["partner", "parent", "friend", "close_family"], recipientTraits: ["sleep", "wellness", "tech", "morning-person", "routine"], occasionFit: ["birthday", "christmas", "housewarming", "just_because"], effortSignal: "moderate_effort", priceTier: "premium", giftable: true, usageSignal: "The last thing they see at night, first thing in the morning", whatThisSays: "I want you to wake up gently" } },

  // ── KIDS: Ages 0-5 ────────────────────────────────────────────────

  { id: "fat-brain-dimpl-digits", name: "Dimpl Digits", brand: "Fat Brain Toys", price: 30, currency: "CAD", category: "kids", imageUrl: "/products/dimpl-digits.jpg", buyUrl: "https://www.amazon.ca/Fat-Brain-Toys-Dimpl-Digits/dp/B081JWCVH2", shortDescription: "Silicone popping sensory toy with embossed numbers 0-9. Satisfying tactile play meets number learning.", meta: { psychologicalFit: ["playful", "thoughtful"], relationshipFit: ["child", "close_family", "friend"], recipientTraits: ["sensory", "numbers", "toddler", "asd-friendly", "fidget"], recipientAge: ["3-5"], occasionFit: ["birthday", "christmas", "just_because"], effortSignal: "moderate_effort", priceTier: "budget", giftable: true, usageSignal: "Pop, count, repeat — endlessly", whatThisSays: "I know they love numbers and this makes counting a sensory joy" } },

  { id: "hape-piano", name: "Learn with Lights Piano", brand: "Hape", price: 137, currency: "CAD", category: "kids", imageUrl: "/products/hape-piano.jpg", buyUrl: "https://littlecanadian.ca/products/hape-learn-with-lights-piano", shortDescription: "25-key wooden electric piano with light-up keys guiding 15 demo songs. 6 instrument sounds.", meta: { psychologicalFit: ["thoughtful", "playful"], relationshipFit: ["child", "close_family", "parent"], recipientTraits: ["piano", "music", "learning", "asd-friendly"], recipientAge: ["3-5", "6-11"], occasionFit: ["birthday", "christmas"], effortSignal: "high_effort", priceTier: "moderate", giftable: true, usageSignal: "Light-up keys guide them through songs — visual learning meets music", whatThisSays: "I see the musician in you already" } },

  { id: "plantoys-sort-count", name: "Sort & Count Trees", brand: "PlanToys", price: 40, currency: "CAD", category: "kids", imageUrl: "/products/plantoys-trees.jpg", buyUrl: "https://plantoys.ca/products/sort-count-trees", shortDescription: "Wooden Montessori sorting set with tree-shaped rods and colorful crown rings. Teaches counting 1-5.", meta: { psychologicalFit: ["thoughtful"], relationshipFit: ["child", "close_family"], recipientTraits: ["numbers", "montessori", "wooden-toys", "learning"], recipientAge: ["0-2", "3-5"], occasionFit: ["birthday", "christmas", "just_because"], effortSignal: "moderate_effort", priceTier: "budget", giftable: true, usageSignal: "Quiet, focused play at the kitchen table", whatThisSays: "Beautiful toys teach beautiful lessons" } },

  { id: "melissa-doug-dinos", name: "Dinosaur Party Play Set", brand: "Melissa & Doug", price: 22, currency: "CAD", category: "kids", imageUrl: "/products/melissa-dinos.jpg", buyUrl: "https://www.amazon.ca/dp/B01B1UPBZQ", shortDescription: "Nine realistic felt-covered miniature dinosaurs in a labeled wooden carrying case. T-Rex included.", meta: { psychologicalFit: ["playful"], relationshipFit: ["child", "close_family", "friend"], recipientTraits: ["dinosaurs", "imaginative-play", "learning"], recipientAge: ["3-5", "6-11"], occasionFit: ["birthday", "christmas", "just_because"], effortSignal: "low_effort", priceTier: "token", giftable: true, usageSignal: "Nine named species to learn, carry around, and roar with", whatThisSays: "I know exactly which dinosaur is their favorite" } },

  { id: "lovevery-connector-kit", name: "The Connector Play Kit (Age 4)", brand: "Lovevery", price: 109, currency: "CAD", category: "kids", imageUrl: "/products/lovevery.jpg", buyUrl: "https://lovevery.com/products/the-play-kits/4-year-old", shortDescription: "Montessori-designed play kit for 4-year-olds. Research-backed activities for flexible thinking and problem-solving.", meta: { psychologicalFit: ["thoughtful"], relationshipFit: ["child", "parent", "close_family"], recipientTraits: ["montessori", "developmental", "learning", "asd-friendly"], recipientAge: ["3-5"], occasionFit: ["birthday", "christmas"], effortSignal: "high_effort", priceTier: "moderate", giftable: true, usageSignal: "Every piece targets a specific cognitive skill — with a parent guide explaining why", whatThisSays: "I care about how they grow, not just what they play with" } },

  // ── KIDS: Ages 6-11 ───────────────────────────────────────────────

  { id: "lego-dino-31058", name: "Creator 3-in-1 Mighty Dinosaurs", brand: "LEGO", price: 20, currency: "CAD", category: "kids", imageUrl: "/products/lego-dino-small.jpg", buyUrl: "https://www.lego.com/en-ca/product/mighty-dinosaurs-31058", shortDescription: "174 pieces — builds a T-Rex with posable joints, rebuilds into Triceratops or Pterodactyl.", meta: { psychologicalFit: ["playful"], relationshipFit: ["child", "close_family", "friend", "acquaintance"], recipientTraits: ["dinosaurs", "building", "lego", "creative"], recipientAge: ["6-11"], occasionFit: ["birthday", "christmas", "just_because"], effortSignal: "low_effort", priceTier: "token", giftable: true, usageSignal: "Three dinosaurs in one box — rebuild a different one every time", whatThisSays: "The perfect small gift for the dino kid" } },

  { id: "lego-trex-31151", name: "Creator 3-in-1 T. Rex", brand: "LEGO", price: 80, currency: "CAD", category: "kids", imageUrl: "/products/lego-trex.jpg", buyUrl: "https://www.lego.com/en-ca/product/t-rex-31151", shortDescription: "626-piece detailed T-Rex with full posability. Rebuilds into Triceratops or Pterodactyl.", meta: { psychologicalFit: ["playful", "thoughtful"], relationshipFit: ["child", "close_family", "parent"], recipientTraits: ["dinosaurs", "building", "lego", "patient", "creative"], recipientAge: ["6-11", "12-17"], occasionFit: ["birthday", "christmas"], effortSignal: "moderate_effort", priceTier: "moderate", giftable: true, usageSignal: "Hours of focused building, then years of display-shelf pride", whatThisSays: "For the builder who's ready for a real challenge" } },

  { id: "nat-geo-earth-science", name: "Earth Science Activity Kit", brand: "National Geographic", price: 70, currency: "CAD", category: "kids", imageUrl: "/products/natgeo-science.jpg", buyUrl: "https://www.amazon.ca/NATIONAL-GEOGRAPHIC-Earth-Science-Kit/dp/B09KTK4B2C", shortDescription: "100+ experiments — crystal growing, volcano building, gemstone digging, plus a real mineral collection.", meta: { psychologicalFit: ["thoughtful", "playful"], relationshipFit: ["child", "close_family", "parent"], recipientTraits: ["science", "curious", "experiments", "stem"], recipientAge: ["6-11"], occasionFit: ["birthday", "christmas"], effortSignal: "high_effort", priceTier: "moderate", giftable: true, usageSignal: "A science lab in a box — weeks of engaged discovery", whatThisSays: "I see a future scientist" } },

  { id: "snap-circuits-jr", name: "Snap Circuits Jr. SC-100", brand: "Elenco", price: 42, currency: "CAD", category: "kids", imageUrl: "/products/snap-circuits.jpg", buyUrl: "https://www.amazon.ca/Elenco-Snap-Circuits-Jr-SC-100/dp/B00008BFZH", shortDescription: "30+ snap-together parts, 100+ circuit projects. Photo sensor, siren, flashing lights. No soldering.", meta: { psychologicalFit: ["thoughtful", "playful"], relationshipFit: ["child", "close_family", "friend"], recipientTraits: ["stem", "electronics", "building", "curious", "tech"], recipientAge: ["6-11"], occasionFit: ["birthday", "christmas"], effortSignal: "moderate_effort", priceTier: "budget", giftable: true, usageSignal: "Real working circuits built with zero frustration", whatThisSays: "For the kid who wants to know how things work" } },

  { id: "kiwico-tinker-crate", name: "Tinker Crate (Single Kit)", brand: "KiwiCo", price: 27, currency: "CAD", category: "kids", imageUrl: "/products/kiwico.jpg", buyUrl: "https://www.kiwico.com/ca/store/cp/tinker", shortDescription: "Monthly STEM engineering kit — hydraulic claws, walking robots, trebuchets. Everything included.", meta: { psychologicalFit: ["thoughtful", "playful"], relationshipFit: ["child", "close_family", "friend"], recipientTraits: ["stem", "engineering", "building", "creative"], recipientAge: ["6-11", "12-17"], occasionFit: ["birthday", "christmas", "just_because"], effortSignal: "moderate_effort", priceTier: "budget", giftable: true, usageSignal: "A self-contained engineering challenge in a beautifully packaged box", whatThisSays: "Here's your next project" } },

  // ── KIDS: Baby / Newborn ──────────────────────────────────────────

  { id: "jellycat-bunny", name: "Bashful Beige Bunny (Medium)", brand: "Jellycat", price: 35, currency: "CAD", category: "kids", imageUrl: "/products/jellycat.jpg", buyUrl: "https://www.indigo.ca/en-ca/bashful-bunny-medium/670983038569.html", shortDescription: "Ultra-soft 12-inch plush bunny with floppy ears. The most universally beloved baby gift.", meta: { psychologicalFit: ["sentimental", "playful"], relationshipFit: ["child", "close_family", "friend", "acquaintance"], recipientTraits: ["baby", "newborn", "soft-toy", "comfort"], recipientAge: ["0-2"], occasionFit: ["baby_shower", "new_baby", "birthday", "christmas"], effortSignal: "moderate_effort", priceTier: "budget", giftable: true, usageSignal: "Becomes the one they can't sleep without", whatThisSays: "Every childhood needs a bunny" } },

  { id: "hatch-rest-baby", name: "Rest+ 2nd Gen Sound Machine & Nightlight", brand: "Hatch", price: 90, currency: "CAD", category: "kids", imageUrl: "/products/hatch-baby.jpg", buyUrl: "https://www.amazon.ca/Hatch-Rest-Sound-Machine-Night/dp/B08GZSM6GT", shortDescription: "Sound machine, nightlight, and time-to-rise alert in one. App-controlled. The #1 registry item.", meta: { psychologicalFit: ["practical", "thoughtful"], relationshipFit: ["child", "close_family", "friend"], recipientTraits: ["baby", "newborn", "nursery", "sleep", "parents"], recipientAge: ["0-2", "3-5"], occasionFit: ["baby_shower", "new_baby", "christmas"], effortSignal: "moderate_effort", priceTier: "moderate", giftable: true, usageSignal: "On every night from day one — and the toddler years too", whatThisSays: "For better sleep — theirs and yours" } },

  // ── PRACTICAL: Tech & Gadgets (new) ───────────────────────────────

  { id: "airpods-4", name: "AirPods 4 with ANC", brand: "Apple", price: 179, currency: "CAD", category: "practical", imageUrl: "/products/airpods4.jpg", buyUrl: "https://www.apple.com/ca/shop/buy-airpods/airpods-4", shortDescription: "Wireless earbuds with Active Noise Cancellation and Adaptive Audio. The everyday essential.", meta: { psychologicalFit: ["practical"], relationshipFit: ["partner", "close_family", "friend", "child"], recipientTraits: ["music", "tech", "commuter", "podcast", "active"], recipientAge: ["12-17", "18-25", "26-40", "41-60"], occasionFit: ["birthday", "christmas", "graduation"], effortSignal: "moderate_effort", priceTier: "premium", giftable: true, usageSignal: "They'll reach for these every single day — commute, calls, workouts", whatThisSays: "The one tech upgrade that genuinely improves your day" } },

  { id: "apple-airtag-4pack", name: "AirTag (4 Pack)", brand: "Apple", price: 129, currency: "CAD", category: "practical", imageUrl: "/products/airtag.jpg", buyUrl: "https://www.apple.com/ca/shop/buy-airtag/airtag", shortDescription: "Precision Finding trackers — attach to keys, bags, luggage, pet collars. Never lose anything again.", meta: { psychologicalFit: ["practical", "playful"], relationshipFit: ["partner", "parent", "close_family", "friend"], recipientTraits: ["tech", "travel", "forgetful", "organized", "adhd"], occasionFit: ["birthday", "christmas", "just_because", "fathers_day"], effortSignal: "moderate_effort", priceTier: "moderate", giftable: true, usageSignal: "Panic-check them weekly, grateful every time they work", whatThisSays: "For the person who can never find their keys" } },

  { id: "kindle-paperwhite", name: "Paperwhite (16GB, 12th Gen)", brand: "Amazon Kindle", price: 185, currency: "CAD", category: "practical", imageUrl: "/products/kindle.jpg", buyUrl: "https://www.amazon.ca/All-new-Amazon-Kindle-Paperwhite-glare-free/dp/B0CFPWLGF2", shortDescription: "7\" glare-free display, adjustable warm light, waterproof, weeks of battery. Replaces the phone at bedtime.", meta: { psychologicalFit: ["practical", "thoughtful"], relationshipFit: ["partner", "parent", "friend", "close_family"], recipientTraits: ["reading", "books", "tech", "travel"], recipientAge: ["18-25", "26-40", "41-60", "61+"], occasionFit: ["birthday", "christmas", "graduation", "retirement", "mothers_day", "fathers_day"], effortSignal: "moderate_effort", priceTier: "premium", giftable: true, usageSignal: "Replaces their phone at bedtime and goes on every vacation", whatThisSays: "I know you want to read more — this removes every excuse" } },

  { id: "sony-wh1000xm5", name: "WH-1000XM5 Wireless Headphones", brand: "Sony", price: 378, currency: "CAD", category: "practical", imageUrl: "/products/sony-xm5.jpg", buyUrl: "https://www.amazon.ca/Sony-WH-1000XM5-Cancelling-Headphones-Hands-Free/dp/B09XS7JWHH", shortDescription: "Industry-leading noise-cancelling headphones. 30-hour battery, multipoint Bluetooth. The gold standard.", meta: { psychologicalFit: ["practical", "luxurious"], relationshipFit: ["partner", "close_family"], recipientTraits: ["music", "tech", "wfh", "travel", "commuter", "audiophile"], occasionFit: ["birthday", "christmas", "anniversary", "graduation"], effortSignal: "high_effort", priceTier: "luxury", giftable: true, usageSignal: "Daily work companion and travel essential for years", whatThisSays: "Your focus — and your music — deserve this" } },

  { id: "anker-nano-powerbank", name: "Nano Power Bank (10,000mAh)", brand: "Anker", price: 65, currency: "CAD", category: "practical", imageUrl: "/products/anker-nano.jpg", buyUrl: "https://www.anker.com/ca/products/a1259-built-in-cable-power-bank-10000mah", shortDescription: "Compact portable charger with built-in USB-C cable and 30W fast charging. Lives permanently in your bag.", meta: { psychologicalFit: ["practical"], relationshipFit: ["friend", "professional", "close_family", "acquaintance"], recipientTraits: ["tech", "travel", "commuter", "practical"], occasionFit: ["birthday", "christmas", "thank_you", "just_because"], effortSignal: "low_effort", priceTier: "moderate", giftable: true, usageSignal: "Lives in their bag and saves them at least once a week", whatThisSays: "Never run out of battery again" } },

  // ── PRACTICAL: Home & Living (new) ────────────────────────────────

  { id: "endy-percale-sheets", name: "Organic Cotton Percale Sheet Set (Queen)", brand: "Endy", price: 125, currency: "CAD", category: "practical", imageUrl: "/products/endy-sheets.jpg", buyUrl: "https://www.endy.com/products/organic-cotton-sheets-percale", shortDescription: "300-thread-count organic long-staple cotton with a crisp, cool percale weave. Made for Canadian sleepers.", meta: { psychologicalFit: ["practical", "luxurious", "thoughtful"], relationshipFit: ["partner", "close_family", "friend"], recipientTraits: ["home", "sleep", "minimalist", "quality"], occasionFit: ["wedding", "housewarming", "birthday", "christmas"], effortSignal: "moderate_effort", priceTier: "moderate", giftable: true, usageSignal: "They'll sleep on these every night and never go back to cheap sheets", whatThisSays: "You deserve to sleep well" } },

  { id: "hay-kaleido-tray", name: "Kaleido Tray (Medium)", brand: "HAY", price: 30, currency: "CAD", category: "practical", imageUrl: "/products/hay-tray.jpg", buyUrl: "https://www.ssense.com/en-ca/everything-else/product/hay/grey-medium-kaleido-tray/9646631", shortDescription: "Geometric lacquered steel tray in bold colours. Catches keys, wallet, watch. Danish design.", meta: { psychologicalFit: ["practical", "thoughtful"], relationshipFit: ["friend", "professional", "acquaintance", "close_family"], recipientTraits: ["design", "minimalist", "home", "organized"], occasionFit: ["housewarming", "christmas", "birthday", "thank_you", "just_because"], effortSignal: "moderate_effort", priceTier: "budget", giftable: true, usageSignal: "Keys, wallet, and watch land here every single day", whatThisSays: "For someone who appreciates small, well-designed things" } },

  // ── ARTISAN: Jewelry & Accessories (new) ──────────────────────────

  { id: "mejuri-croissant-dome", name: "Croissant Dôme Ring", brand: "Mejuri", price: 78, currency: "CAD", category: "artisan", imageUrl: "/products/mejuri-ring.jpg", buyUrl: "https://mejuri.com/shop/products/croissant-dome-ring", shortDescription: "14k gold vermeil sculptural ring. Mejuri is Canadian — designed in Toronto, ethically sourced.", meta: { psychologicalFit: ["luxurious", "sentimental"], relationshipFit: ["partner", "close_family", "friend"], recipientTraits: ["jewelry", "fashion", "design", "minimalist"], recipientAge: ["18-25", "26-40", "41-60"], occasionFit: ["birthday", "valentines", "anniversary", "christmas", "just_because", "mothers_day"], effortSignal: "high_effort", priceTier: "moderate", giftable: true, usageSignal: "Worn every day — the ring she never takes off", whatThisSays: "I chose this because it's as effortlessly beautiful as you" } },

  { id: "mejuri-bold-hoop", name: "Bold Hoop Earrings", brand: "Mejuri", price: 65, currency: "CAD", category: "artisan", imageUrl: "/products/mejuri-hoops.jpg", buyUrl: "https://mejuri.com/shop/products/bold-hoops", shortDescription: "14k gold vermeil everyday hoops. Lightweight, comfortable enough to sleep in. Canadian-designed.", meta: { psychologicalFit: ["luxurious", "thoughtful"], relationshipFit: ["partner", "close_family", "friend"], recipientTraits: ["jewelry", "fashion", "minimalist"], recipientAge: ["18-25", "26-40", "41-60"], occasionFit: ["birthday", "valentines", "christmas", "mothers_day", "just_because"], effortSignal: "moderate_effort", priceTier: "moderate", giftable: true, usageSignal: "The hoops she reaches for every morning without thinking", whatThisSays: "Classic, effortless, just like you" } },

  { id: "bellroy-slim-wallet", name: "Slim Sleeve Wallet", brand: "Bellroy", price: 89, currency: "CAD", category: "artisan", imageUrl: "/products/bellroy.jpg", buyUrl: "https://bellroy.com/products/slim-sleeve-wallet", shortDescription: "Premium leather slim wallet — holds 4-12 cards with pull-tab access. Environmentally certified tanneries.", meta: { psychologicalFit: ["practical", "luxurious"], relationshipFit: ["partner", "parent", "friend", "professional"], recipientTraits: ["minimalist", "fashion", "organized", "practical", "travel"], recipientAge: ["18-25", "26-40", "41-60"], occasionFit: ["birthday", "christmas", "fathers_day", "graduation", "thank_you"], effortSignal: "moderate_effort", priceTier: "moderate", giftable: true, usageSignal: "In their pocket every single day for years", whatThisSays: "An upgrade they'd never buy themselves" } },

  { id: "aesop-resurrection-duo", name: "Resurrection Aromatique Hand Care Duo", brand: "Aesop", price: 67, currency: "CAD", category: "artisan", imageUrl: "/products/aesop-duo.jpg", buyUrl: "https://shop.aesop.com/ca/p/gift-kits/resurrection-aromatique-hand-care-duo/", shortDescription: "Hand wash + hand balm in Aesop's signature amber bottles. Citrus and woody scent. The quintessential host gift.", meta: { psychologicalFit: ["luxurious", "thoughtful"], relationshipFit: ["friend", "professional", "acquaintance", "partner", "parent", "close_family"], recipientTraits: ["design", "skincare", "home", "luxury", "aesthetic"], occasionFit: ["housewarming", "thank_you", "birthday", "christmas", "mothers_day", "just_because"], effortSignal: "moderate_effort", priceTier: "moderate", giftable: true, usageSignal: "By the kitchen or bathroom sink — used multiple times a day", whatThisSays: "I notice you care about the details" } },

  { id: "pf-candle-amber", name: "Amber & Moss Soy Candle (7.2oz)", brand: "P.F. Candle Co.", price: 32, currency: "CAD", category: "artisan", imageUrl: "/products/pf-candle.jpg", buyUrl: "https://www.amazon.ca/P-F-Candle-Co-Amber-Moss/dp/B00NI0EWNY", shortDescription: "Bestselling apothecary-style soy candle — musky, earthy, warm. Gender-neutral. The one everyone loves.", meta: { psychologicalFit: ["thoughtful"], relationshipFit: ["friend", "professional", "acquaintance", "close_family"], recipientTraits: ["home", "cozy", "design", "minimalist"], occasionFit: ["housewarming", "thank_you", "birthday", "christmas", "just_because"], effortSignal: "low_effort", priceTier: "budget", giftable: true, usageSignal: "Lit every evening during dinner or reading time", whatThisSays: "A small luxury for your space" } },

  { id: "boy-smells-candle", name: "LES Candle (8.5oz)", brand: "Boy Smells", price: 45, currency: "CAD", category: "artisan", imageUrl: "/products/boy-smells.jpg", buyUrl: "https://www.ssense.com/en-ca/everything-else/product/boy-smells/les-candle-85-oz/11173821", shortDescription: "Cedar, white musk, and dark amber. Pink wax in a matte black box. Intentionally gender-free.", meta: { psychologicalFit: ["luxurious", "thoughtful"], relationshipFit: ["partner", "friend", "professional", "close_family"], recipientTraits: ["home", "design", "aesthetic", "luxury", "candle-lover"], occasionFit: ["housewarming", "birthday", "valentines", "thank_you", "christmas", "just_because"], effortSignal: "moderate_effort", priceTier: "budget", giftable: true, usageSignal: "The candle that makes the whole room smell like intention", whatThisSays: "I know your taste goes beyond the mainstream" } },

  // ── PRACTICAL: Music & Creative (new) ─────────────────────────────

  { id: "kala-ukulele", name: "Learn to Play Starter Kit", brand: "Kala", price: 85, currency: "CAD", category: "practical", imageUrl: "/products/kala-uke.jpg", buyUrl: "https://www.amazon.ca/Official-Kala-Learn-Ukulele-Starter/dp/B01N7ULZJA", shortDescription: "Concert ukulele with online lessons, tuner app, and quick-start guide. Play a song in 15 minutes.", meta: { psychologicalFit: ["playful", "adventurous"], relationshipFit: ["friend", "partner", "close_family", "child"], recipientTraits: ["music", "creative", "curious", "fun"], recipientAge: ["12-17", "18-25", "26-40", "41-60"], occasionFit: ["birthday", "christmas", "just_because", "graduation"], effortSignal: "high_effort", priceTier: "moderate", giftable: true, usageSignal: "Strumming on the couch within 15 minutes of opening it", whatThisSays: "Life is better with music in it" } },

  { id: "vinyl-me-please-3mo", name: "3-Month Gift Subscription", brand: "Vinyl Me, Please", price: 120, currency: "CAD", category: "practical", imageUrl: "/products/vmp.jpg", buyUrl: "https://www.vinylmeplease.com/gift", shortDescription: "Monthly curated vinyl records — exclusive pressings on colored wax with art prints. For the music collector.", meta: { psychologicalFit: ["thoughtful", "adventurous"], relationshipFit: ["partner", "friend", "close_family"], recipientTraits: ["music", "vinyl", "audiophile", "collecting", "design"], occasionFit: ["birthday", "christmas", "valentines", "fathers_day", "just_because"], effortSignal: "high_effort", priceTier: "moderate", giftable: true, usageSignal: "A new record to spin and discover every month", whatThisSays: "For the person whose shelf is their autobiography" } },

  // ── PRACTICAL: Music & Creative (continued) ───────────────────────

  { id: "zoom-h1-recorder", name: "H1essential Portable Recorder", brand: "Zoom", price: 107, currency: "CAD", category: "practical", imageUrl: "/products/zoom-h1.jpg", buyUrl: "https://www.amazon.ca/Zoom-H1essential-Accessibility-Microphones-Microphone/dp/B0CSL4PXDV", shortDescription: "32-bit float stereo recorder — never clips audio. Capture song ideas, podcasts, field recordings on the fly.", meta: { psychologicalFit: ["practical", "thoughtful"], relationshipFit: ["partner", "friend", "close_family"], recipientTraits: ["music", "podcast", "creative", "recording", "songwriter"], occasionFit: ["birthday", "christmas", "just_because"], effortSignal: "high_effort", priceTier: "moderate", giftable: true, usageSignal: "They'll carry this to rehearsals and capture ideas the moment inspiration strikes", whatThisSays: "Your ideas deserve to be captured" } },

  { id: "daddario-micro-tuner", name: "NS Micro Headstock Tuner", brand: "D'Addario", price: 32, currency: "CAD", category: "practical", imageUrl: "/products/daddario-tuner.jpg", buyUrl: "https://guitarworks.ca/products/daddario-ns-micro-headstock-tuner", shortDescription: "Ultra-compact clip-on chromatic tuner that nearly disappears on the headstock. Works on any string instrument.", meta: { psychologicalFit: ["practical"], relationshipFit: ["friend", "close_family", "acquaintance"], recipientTraits: ["guitar", "music", "ukulele", "bass"], occasionFit: ["birthday", "christmas", "just_because"], effortSignal: "low_effort", priceTier: "budget", giftable: true, usageSignal: "Lives clipped to their guitar — used every time they play", whatThisSays: "A small thing that makes every session better" } },

  { id: "rhymebook-journal", name: "RHYMEBOOK Songwriting Journal", brand: "DailyRapFacts", price: 35, currency: "CAD", category: "practical", imageUrl: "/products/rhymebook.jpg", buyUrl: "https://store.dailyrapfacts.com/products/rhymebook-black", shortDescription: "220-page hardcover journal designed for lyricists — 3/4 lined, 1/4 blank, with pen and 'How to Write' guide.", meta: { psychologicalFit: ["thoughtful", "playful"], relationshipFit: ["friend", "partner", "close_family"], recipientTraits: ["songwriting", "lyrics", "music", "creative", "poetry"], occasionFit: ["birthday", "christmas", "just_because"], effortSignal: "moderate_effort", priceTier: "budget", giftable: true, usageSignal: "Rides in their bag for capturing lyrics the moment inspiration strikes", whatThisSays: "Your words matter — write them down" } },

  // ── PRACTICAL: Kitchen (continued) ────────────────────────────────

  { id: "zwilling-chef-knife", name: "Pro 7\" Chef's Knife", brand: "Zwilling", price: 130, currency: "CAD", category: "practical", imageUrl: "/products/zwilling.jpg", buyUrl: "https://www.zwilling.com/ca/zwilling-pro-7-inch-chefs-knife-38431-182/38431-182-0.html", shortDescription: "Forged German stainless steel chef's knife with ergonomic bolster. The one knife every cook needs.", meta: { psychologicalFit: ["practical", "luxurious"], relationshipFit: ["partner", "parent", "friend", "close_family"], recipientTraits: ["cooking", "foodie", "home", "practical"], occasionFit: ["birthday", "housewarming", "wedding", "christmas", "mothers_day", "fathers_day"], effortSignal: "moderate_effort", priceTier: "moderate", giftable: true, usageSignal: "THE knife they reach for — every meal, every day", whatThisSays: "Your cooking deserves a proper tool" } },

  { id: "staub-dutch-oven", name: "La Cocotte Round Dutch Oven (3.7L)", brand: "Staub", price: 300, currency: "CAD", category: "practical", imageUrl: "/products/staub.jpg", buyUrl: "https://www.zwilling.com/ca/staub/cast-iron/cocottes-dutch-ovens/", shortDescription: "Enameled cast-iron French oven. Self-basting lid. Sourdough, braises, one-pot meals. Made in France.", meta: { psychologicalFit: ["practical", "luxurious", "thoughtful"], relationshipFit: ["partner", "parent", "close_family"], recipientTraits: ["cooking", "foodie", "baking", "home", "design"], occasionFit: ["wedding", "birthday", "christmas", "housewarming"], effortSignal: "high_effort", priceTier: "premium", giftable: true, usageSignal: "Sourdough on Saturday, braised short ribs on Sunday — heavy rotation every week", whatThisSays: "For the cook who's ready for something heirloom" } },

  { id: "chemex-6cup", name: "Classic 6-Cup Pour-Over Coffeemaker", brand: "Chemex", price: 66, currency: "CAD", category: "practical", imageUrl: "/products/chemex.jpg", buyUrl: "https://well.ca/products/chemex-6-cup-classic-coffeemaker_116584.html", shortDescription: "Iconic borosilicate glass brewer with wood collar and leather tie. Brews clean, bright coffee. MoMA collection.", meta: { psychologicalFit: ["practical", "thoughtful"], relationshipFit: ["friend", "partner", "professional", "close_family"], recipientTraits: ["coffee", "design", "minimalist", "morning-person"], occasionFit: ["birthday", "housewarming", "christmas", "thank_you"], effortSignal: "moderate_effort", priceTier: "moderate", giftable: true, usageSignal: "The centerpiece of their morning coffee counter", whatThisSays: "Your coffee ritual deserves something beautiful" } },

  { id: "hedley-bennett-apron", name: "Essential Apron", brand: "Hedley & Bennett", price: 124, currency: "CAD", category: "practical", imageUrl: "/products/hedley-bennett.jpg", buyUrl: "https://www.maisoncookware.com/collections/hedley-bennett-aprons-canada", shortDescription: "Professional-grade cotton canvas apron with cross-back straps and 3 pockets. Chef-approved, home-ready.", meta: { psychologicalFit: ["practical", "thoughtful"], relationshipFit: ["partner", "parent", "friend", "close_family"], recipientTraits: ["cooking", "foodie", "baking", "grilling", "home"], occasionFit: ["birthday", "housewarming", "christmas", "mothers_day", "fathers_day"], effortSignal: "moderate_effort", priceTier: "moderate", giftable: true, usageSignal: "They'll throw this on every time they cook — makes them feel like a real chef", whatThisSays: "Your kitchen is your stage" } },

  // ── PRACTICAL: Outdoor (continued) ────────────────────────────────

  { id: "hydro-flask-32oz", name: "Wide Mouth 32oz Bottle", brand: "Hydro Flask", price: 55, currency: "CAD", category: "practical", imageUrl: "/products/hydroflask.jpg", buyUrl: "https://www.sportchek.ca/en/pdp/hydro-flask-wide-mouth-32-oz-insulated-water-bottle-10793855f.html", shortDescription: "Double-wall vacuum insulated — cold 24 hours, hot 12 hours. Goes from desk to trail to gym.", meta: { psychologicalFit: ["practical"], relationshipFit: ["friend", "close_family", "partner", "acquaintance"], recipientTraits: ["active", "outdoors", "gym", "hiking", "hydration"], occasionFit: ["birthday", "christmas", "just_because", "graduation"], effortSignal: "low_effort", priceTier: "moderate", giftable: true, usageSignal: "Goes everywhere — desk, gym, trail, car cupholder", whatThisSays: "Stay hydrated, stay moving" } },

  { id: "peak-design-sling", name: "Everyday Sling 6L", brand: "Peak Design", price: 180, currency: "CAD", category: "practical", imageUrl: "/products/peak-sling.jpg", buyUrl: "https://www.canadaluggagedepot.ca/products/peak-design-everyday-sling-6l", shortDescription: "Premium crossbody sling with FlexFold dividers and 100% recycled nylon. The photographer's daily carry.", meta: { psychologicalFit: ["practical", "luxurious"], relationshipFit: ["partner", "friend", "close_family"], recipientTraits: ["photography", "travel", "tech", "minimalist", "commuter"], occasionFit: ["birthday", "christmas", "graduation"], effortSignal: "moderate_effort", priceTier: "premium", giftable: true, usageSignal: "Camera, tablet, essentials — this becomes their everyday carry for every outing", whatThisSays: "For someone who takes their gear as seriously as their craft" } },

  { id: "stanley-quencher", name: "Quencher H2.0 Travel Tumbler (40oz)", brand: "Stanley", price: 55, currency: "CAD", category: "practical", imageUrl: "/products/stanley.jpg", buyUrl: "https://ca.stanley1913.com/collections/adventure-quencher-travel-tumblers", shortDescription: "The tumbler that took over — insulated, car-cupholder friendly, straw included. Keeps cold 24 hours.", meta: { psychologicalFit: ["practical"], relationshipFit: ["friend", "close_family", "acquaintance", "professional"], recipientTraits: ["hydration", "office", "commuter", "active", "practical"], occasionFit: ["birthday", "christmas", "thank_you", "just_because"], effortSignal: "low_effort", priceTier: "moderate", giftable: true, usageSignal: "Sits on their desk or car console literally all day, every day", whatThisSays: "Welcome to the Stanley cult" } },

  // ── CONSUMABLE: Flowers & Plants (new) ────────────────────────────

  { id: "wild-north-flowers", name: "Florist's Choice Glass Vase Arrangement", brand: "Wild North Flowers", price: 110, currency: "CAD", category: "consumable", imageUrl: "/products/wild-north.jpg", buyUrl: "https://www.wildnorthflowers.com/products/florists-choice-glass-vase-arrangement", shortDescription: "Seasonal arrangement from Toronto's best florist — 6+ flower varieties in a glass vase. Same-day delivery.", meta: { psychologicalFit: ["sentimental", "thoughtful", "luxurious"], relationshipFit: ["partner", "parent", "close_family", "friend", "professional"], recipientTraits: ["flowers", "home", "aesthetic", "romantic"], occasionFit: ["birthday", "mothers_day", "valentines", "anniversary", "thank_you", "just_because"], effortSignal: "moderate_effort", priceTier: "moderate", giftable: true, usageSignal: "A week of beauty on the kitchen table", whatThisSays: "I wanted you to have something beautiful today" } },

  { id: "olfco-dried-bouquet", name: "Dried Bouquet", brand: "Our Little Flower Company", price: 75, currency: "CAD", category: "consumable", imageUrl: "/products/olfco.jpg", buyUrl: "https://olfco.ca/products/dried-bouquet", shortDescription: "Long-stem dried flowers in natural tones — lasts 1-2 years with zero care. Compostable packaging.", meta: { psychologicalFit: ["thoughtful", "sentimental"], relationshipFit: ["friend", "partner", "close_family", "professional"], recipientTraits: ["design", "home", "minimalist", "sustainable"], occasionFit: ["birthday", "housewarming", "thank_you", "just_because", "mothers_day"], effortSignal: "moderate_effort", priceTier: "moderate", giftable: true, usageSignal: "These last forever — no water, no wilting, just permanent beauty", whatThisSays: "For someone who loves flowers but hates watching them die" } },

  { id: "jomo-monstera", name: "Monstera Thai Constellation (4\" pot)", brand: "JOMO Studio", price: 25, currency: "CAD", category: "consumable", imageUrl: "/products/jomo-monstera.jpg", buyUrl: "https://jomostudio.com/collections/plants", shortDescription: "Trendy variegated Monstera from a Toronto shop. Carbon-neutral shipping, lifetime care support, 15-day guarantee.", meta: { psychologicalFit: ["playful", "thoughtful"], relationshipFit: ["friend", "partner", "close_family", "professional"], recipientTraits: ["plants", "home", "design", "nature"], occasionFit: ["housewarming", "birthday", "thank_you", "just_because"], effortSignal: "moderate_effort", priceTier: "token", giftable: true, usageSignal: "The plant everyone wants but never buys themselves — with lifetime care support", whatThisSays: "Here's something alive to take care of" } },

  { id: "terrarium-kit", name: "Easy Build Closed Terrarium Kit", brand: "Terrarium Kit", price: 75, currency: "CAD", category: "consumable", imageUrl: "/products/terrarium.jpg", buyUrl: "https://terrariumkit.ca/collections/frontpage", shortDescription: "DIY closed terrarium with live moss and everything included. Self-sustaining ecosystem in a glass jar.", meta: { psychologicalFit: ["playful", "thoughtful", "adventurous"], relationshipFit: ["friend", "close_family", "partner", "child"], recipientTraits: ["plants", "science", "creative", "home", "curious"], occasionFit: ["birthday", "housewarming", "christmas", "just_because"], effortSignal: "high_effort", priceTier: "moderate", giftable: true, usageSignal: "Build it, close the lid, and it waters itself. A tiny self-sustaining world.", whatThisSays: "For the person who kills every plant — this one is unkillable" } },

  // ── CONSUMABLE: Food & Spirits (continued) ────────────────────────

  { id: "phil-seb-tasting", name: "Classic Coffee Tasting Set", brand: "Phil & Sebastian", price: 30, currency: "CAD", category: "consumable", imageUrl: "/products/phil-seb.jpg", buyUrl: "https://philsebastian.com/collections/coffee", shortDescription: "Curated sampler of single-origin coffees from Calgary's top roaster. Taste your way through three origins.", meta: { psychologicalFit: ["thoughtful"], relationshipFit: ["friend", "professional", "close_family"], recipientTraits: ["coffee", "foodie", "curious"], occasionFit: ["birthday", "christmas", "thank_you", "just_because"], effortSignal: "moderate_effort", priceTier: "budget", giftable: true, usageSignal: "A flight of coffees — taste, compare, pick a favourite", whatThisSays: "From Calgary's finest — find your new favourite origin" } },

  { id: "saltspring-hot-sauce", name: "Hot Sauce Trio Collection", brand: "SaltSpring Kitchen Co.", price: 32, currency: "CAD", category: "consumable", imageUrl: "/products/saltspring.jpg", buyUrl: "https://saltspringkitchen.com/products/hot-sauce-trio-collection-gift-box", shortDescription: "Three small-batch BC hot sauces — Pineapple Turmeric, Morita Espresso, Habanero Curry Orange. Gift-boxed.", meta: { psychologicalFit: ["playful", "thoughtful"], relationshipFit: ["friend", "close_family", "partner", "professional"], recipientTraits: ["foodie", "cooking", "spicy", "adventurous"], occasionFit: ["birthday", "christmas", "housewarming", "thank_you", "just_because", "fathers_day"], effortSignal: "moderate_effort", priceTier: "budget", giftable: true, usageSignal: "The espresso chipotle one will change how they think about hot sauce", whatThisSays: "For the person who puts hot sauce on everything — but hasn't tried the good stuff" } },

  { id: "bittermilk-old-fashioned", name: "Bourbon Barrel Aged Old Fashioned Mixer", brand: "Bittermilk", price: 29, currency: "CAD", category: "consumable", imageUrl: "/products/bittermilk.jpg", buyUrl: "https://well.ca/brand/bittermilk.html", shortDescription: "Bartender-made cocktail mixer aged in bourbon barrels. Add whiskey, stir, done. A cocktail cheat code.", meta: { psychologicalFit: ["playful", "luxurious"], relationshipFit: ["friend", "close_family", "professional", "partner"], recipientTraits: ["cocktails", "whiskey", "hosting", "foodie"], occasionFit: ["birthday", "christmas", "housewarming", "thank_you", "just_because", "fathers_day"], effortSignal: "moderate_effort", priceTier: "budget", giftable: true, usageSignal: "A proper Old Fashioned in 30 seconds — just add bourbon", whatThisSays: "Your home bar just got an upgrade" } },

  { id: "cocktail-emporium-smoky", name: "Smoky Old Fashioned Set", brand: "Cocktail Emporium", price: 72, currency: "CAD", category: "consumable", imageUrl: "/products/cocktail-emporium.jpg", buyUrl: "https://www.cocktailemporium.com/collections/cocktail-gift-sets", shortDescription: "Premium ingredient set for smoky Old Fashioneds — Canadian bitters, syrups, and garnishes. Just add whiskey.", meta: { psychologicalFit: ["luxurious", "thoughtful"], relationshipFit: ["partner", "friend", "close_family", "professional"], recipientTraits: ["cocktails", "whiskey", "hosting", "foodie", "home-bar"], occasionFit: ["birthday", "christmas", "housewarming", "thank_you", "fathers_day"], effortSignal: "high_effort", priceTier: "moderate", giftable: true, usageSignal: "Everything they need for a proper smoky Old Fashioned — just add the whiskey", whatThisSays: "For the whiskey enthusiast ready to level up their home bar" } },

  // ── EXPERIENTIAL: Board Games & Entertainment (continued) ─────────

  { id: "wingspan-board-game", name: "Wingspan", brand: "Stonemaier Games", price: 65, currency: "CAD", category: "experiential", imageUrl: "/products/wingspan.jpg", buyUrl: "https://www.amazon.ca/Greater-Than-Games-GREUG-STM910/dp/B07YQ641NQ", shortDescription: "Award-winning engine-building board game about attracting birds. Gorgeous art, satisfying strategy. 1-5 players.", meta: { psychologicalFit: ["playful", "thoughtful"], relationshipFit: ["partner", "friend", "close_family"], recipientTraits: ["games", "nature", "strategy", "social", "creative"], occasionFit: ["birthday", "christmas", "housewarming"], effortSignal: "moderate_effort", priceTier: "moderate", giftable: true, usageSignal: "Game night centrepiece for months — 170 unique bird cards to discover", whatThisSays: "For someone who deserves better than Monopoly" } },

  { id: "codenames-board-game", name: "Codenames", brand: "Czech Games Edition", price: 32, currency: "CAD", category: "experiential", imageUrl: "/products/codenames.jpg", buyUrl: "https://www.amazon.ca/Czech-Games-Codenames-Party-Game/dp/B014Q1XX9S", shortDescription: "Fast-paced team word-association party game. Endlessly replayable, works with any group size. 4+ players.", meta: { psychologicalFit: ["playful"], relationshipFit: ["friend", "close_family", "acquaintance"], recipientTraits: ["games", "social", "party", "words", "fun"], occasionFit: ["christmas", "housewarming", "birthday", "just_because"], effortSignal: "low_effort", priceTier: "budget", giftable: true, usageSignal: "The game that comes out at every dinner party and never gets old", whatThisSays: "For the host who needs a game that works with any crowd" } },

  { id: "scandinave-spa-card", name: "Gift Card ($200)", brand: "Scandinave Spa", price: 200, currency: "CAD", category: "experiential", imageUrl: "/products/scandinave.jpg", buyUrl: "https://www.scandinave.com/offer-relaxation", shortDescription: "Nordic thermal spa experience — valid at all four Canadian locations. Whistler, Tremblant, Blue Mountain, Montreal.", meta: { psychologicalFit: ["luxurious", "thoughtful"], relationshipFit: ["partner", "parent", "close_family", "friend"], recipientTraits: ["wellness", "spa", "relaxation", "experiences", "outdoors"], occasionFit: ["birthday", "anniversary", "mothers_day", "valentines", "retirement", "just_because"], effortSignal: "high_effort", priceTier: "premium", giftable: true, isLastMinute: true, usageSignal: "A full day of hot/cold plunge, steam, and silence — total reset", whatThisSays: "You deserve to stop. Completely." } },

  // ── KIDS: Baby (continued) ────────────────────────────────────────

  { id: "aden-anais-swaddles", name: "Essentials 4-Pack Muslin Swaddles", brand: "Aden + Anais", price: 50, currency: "CAD", category: "kids", imageUrl: "/products/aden-anais.jpg", buyUrl: "https://www.babiesrus.ca/en/Aden-Anais-Essentials-4-Pack-Muslin-Swaddle-Safari-Babes/2A9AF213.html", shortDescription: "Four large breathable cotton muslin swaddles — doubles as nursing cover, burp cloth, stroller shade. Gets softer with each wash.", meta: { psychologicalFit: ["practical", "thoughtful"], relationshipFit: ["close_family", "friend", "acquaintance"], recipientTraits: ["baby", "newborn", "parents"], recipientAge: ["0-2"], occasionFit: ["baby_shower", "new_baby"], effortSignal: "moderate_effort", priceTier: "budget", giftable: true, usageSignal: "Every new parent needs these in multiples — there's always a clean one ready", whatThisSays: "The gift every parent actually uses" } },

  { id: "lovevery-looker-kit", name: "The Looker Play Kit (Newborn)", brand: "Lovevery", price: 109, currency: "CAD", category: "kids", imageUrl: "/products/lovevery-newborn.jpg", buyUrl: "https://lovevery.com/products/the-play-kits-the-looker", shortDescription: "Montessori newborn kit — contrast cards, organic mittens, wooden batting ring, and a parent play guide.", meta: { psychologicalFit: ["thoughtful"], relationshipFit: ["close_family", "friend"], recipientTraits: ["baby", "newborn", "developmental", "montessori"], recipientAge: ["0-2"], occasionFit: ["baby_shower", "new_baby"], effortSignal: "high_effort", priceTier: "moderate", giftable: true, usageSignal: "Expert guidance on exactly how to play with a newborn in the critical first weeks", whatThisSays: "I care about how they grow from day one" } },

  // ── WELLNESS: Sleep & Recovery (continued) ────────────────────────

  { id: "slip-silk-pillowcase", name: "Pure Silk Pillowcase (Queen)", brand: "Slip", price: 150, currency: "CAD", category: "wellness", imageUrl: "/products/slip.jpg", buyUrl: "https://slipsilkpillowcase.ca/collections/queen-pillowcases", shortDescription: "22-momme pure mulberry silk — reduces hair friction, prevents sleep creases, feels luxuriously cool. The OG beauty sleep upgrade.", meta: { psychologicalFit: ["luxurious", "thoughtful"], relationshipFit: ["partner", "parent", "close_family", "friend"], recipientTraits: ["skincare", "sleep", "beauty", "luxury", "self-care"], occasionFit: ["birthday", "christmas", "valentines", "mothers_day", "just_because"], effortSignal: "moderate_effort", priceTier: "moderate", giftable: true, usageSignal: "Once she sleeps on silk, she'll never go back to cotton", whatThisSays: "You deserve to wake up feeling pampered" } },

  { id: "ostrichpillow-eye-mask", name: "Eye Mask", brand: "Ostrichpillow", price: 65, currency: "CAD", category: "wellness", imageUrl: "/products/ostrichpillow.jpg", buyUrl: "https://ostrichpillow.com/products/eye-mask", shortDescription: "3D ergonomic blackout sleep mask — six layers, 30 grams, zero pressure on eyelids. Total darkness anywhere.", meta: { psychologicalFit: ["practical", "thoughtful"], relationshipFit: ["friend", "professional", "partner", "close_family", "acquaintance"], recipientTraits: ["sleep", "travel", "light-sleeper", "wellness"], occasionFit: ["birthday", "christmas", "just_because", "thank_you"], effortSignal: "moderate_effort", priceTier: "moderate", giftable: true, usageSignal: "Packed in every carry-on — they'll refuse to nap without it", whatThisSays: "For the person who takes sleep seriously" } },

  { id: "renpho-eye-massager", name: "Eyeris 1 Eye Massager", brand: "Renpho", price: 80, currency: "CAD", category: "wellness", imageUrl: "/products/renpho.jpg", buyUrl: "https://renpho.ca/products/eyeris-1-eye-massager", shortDescription: "Heated eye massager with air compression, vibration, and Bluetooth music. 15 minutes = full reset.", meta: { psychologicalFit: ["practical", "luxurious"], relationshipFit: ["partner", "parent", "friend", "close_family", "professional"], recipientTraits: ["screen-worker", "headaches", "eye-strain", "wfh", "relaxation"], occasionFit: ["birthday", "christmas", "just_because", "mothers_day", "fathers_day"], effortSignal: "moderate_effort", priceTier: "moderate", giftable: true, usageSignal: "15 minutes after work every day — they'll call it their 'reset button'", whatThisSays: "For eyes that stare at screens all day — permission to close them" } },
];

// ── Catalog helpers ────────────────────────────────────────────────

export function getProductById(id: string): Product | undefined {
  return CATALOG.find((p) => p.id === id);
}

export function filterByPriceTier(tiers: PriceTier[]): Product[] {
  return CATALOG.filter((p) => tiers.includes(p.meta.priceTier));
}

export function filterByOccasion(occasion: string): Product[] {
  const normalized = occasion.toLowerCase().replace(/[^a-z_]/g, "_");
  return CATALOG.filter((p) =>
    p.meta.occasionFit.some((o) => normalized.includes(o.replace("_", "")))
  );
}

export function filterByCategory(category: Product["category"]): Product[] {
  return CATALOG.filter((p) => p.category === category);
}

export function filterByAge(ageRange: string): Product[] {
  return CATALOG.filter((p) =>
    p.meta.recipientAge?.includes(ageRange)
  );
}

// Catalog stats
export function getCatalogStats() {
  const categories: Record<string, number> = {};
  const priceTiers: Record<string, number> = {};
  for (const p of CATALOG) {
    categories[p.category] = (categories[p.category] || 0) + 1;
    priceTiers[p.meta.priceTier] = (priceTiers[p.meta.priceTier] || 0) + 1;
  }
  return { total: CATALOG.length, categories, priceTiers };
}
